### ISSUE TITLE
I am getting an error.

### ISSUE THREAD

**Issue by tigerkig** [RickyBhatti/Commit-Bot#1]
File "commit_bot.py", line 32
    f.write(f"{CRON_JOB_TIME} cd {Path.cwd()} && python commit_bot.py\n")
                                                                                                                      ^                                    
SyntaxError: invalid syntax

**Comment by RickyBhatti** [comment]
You'd have to give me more context than that, as I've just tested the script and it still functions.

- What OS are you using?
- What Python version are you using or have used to test the script?
- Have you tested running the script with and without sudo?

Thanks.

**Comment by RickyBhatti** [comment]
You went ahead and changed the title, but failed to provide any information to help fix the issue.

If no information is provided within the next 3 days, this issue will be closed.
