### ISSUE TITLE
The script to run the program does not work every day , i have to do it manualy , write and run the script in terminal , im using linux system 

### ISSUE THREAD

**Issue by Mhamad6000** [RickyBhatti/Commit-Bot#2]

**Comment by RickyBhatti** [comment]
You'd have to give me more context than that, as I just tested the script again and it still functions on my end.

- What OS are you using?
- What Python version are you using or have used to test the script?
- Have you tested running the script with and without sudo?
- What other troubleshooting have you done? 

Thanks.

**Comment by RickyBhatti** [comment]
Due to the lack of details, this issue is being closed now. Feel free to re-open this issue with any relevant information.
